# Generated by Django 4.0.5 on 2022-06-22 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('brandImage', models.ImageField(upload_to='brand_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('categoryImage', models.ImageField(upload_to='category_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colorName', models.CharField(max_length=100, unique=True)),
                ('hexColor', models.CharField(max_length=7, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(unique=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField(unique=True)),
                ('country', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[("Men's", 'mens'), ("Women's", 'womens')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('actualPrice', models.FloatField()),
                ('sellingPrice', models.FloatField()),
                ('rating', models.IntegerField(default=0)),
                ('addedBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('colors', models.ManyToManyField(related_name='product_color', to='store.color')),
                ('mainImage', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='store.image')),
                ('otherImages', models.ManyToManyField(related_name='product_images', to='store.image')),
                ('relatedBrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.brand')),
                ('relatedCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
                ('sizes', models.ManyToManyField(related_name='product_size', to='store.size')),
            ],
        ),
    ]
