# Generated by Django 3.1.4 on 2022-06-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0003_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='is_admin',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='user-default-img/user_default_img.png', upload_to='user-profile-img/'),
        ),
    ]
